# Generated by Django 3.1 on 2021-03-11 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210311_1338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0002_ingredients_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
