# Generated by Django 3.1 on 2021-03-11 14:56

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20210311_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
