# Generated by Django 3.1 on 2021-03-11 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=user_profile.models.code_generator, max_length=6)),
                ('favourite_cookbook', models.ManyToManyField(blank=True, related_name='liked_by', to='cookbook.CookBook')),
                ('favourite_recipe', models.ManyToManyField(blank=True, related_name='liked_by', to='recipe.Recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
